# VERBOSITY
/run/verbose 0
/event/verbose 0
/tracking/verbose 1
/process/em/verbose 0

# GENERATION
/Generator/SingleParticle/particle e-
/Generator/SingleParticle/min_energy 400 eV
/Generator/SingleParticle/max_energy 400 eV
/Generator/SingleParticle/region AD_HOC

# Nexus Physics List
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  true

# GEOMETRY
/Geometry/KingCRAB/gas_pressure 5 bar
/Geometry/KingCRAB/max_step_size 0.1 mm
/Geometry/KingCRAB/specific_vertex_ 0 0 4 mm
/Geometry/KingCRAB/EL_field_intensity 900 kV/m

# PERSISTENCY
/nexus/random_seed            9
/nexus/persistency/start_id   0
/nexus/persistency/output_file KingCRAB_ElectronTracks
