## ----------------------------------------------------------------------------
## nexus | KingCRAB_GammaGen.config.mac
##
## Configuration macro to generate photons in KingCRAB
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

# VERBOSITY
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

# GENERATION
/Generator/SingleParticle/region AD_HOC
/Geometry/KingCRAB/specific_vertex_ 0 -231 1250 mm
/Geometry/KingCRAB/EL_field_intensity 900 kV/m
/Generator/SingleParticle/particle gamma
/Generator/SingleParticle/min_energy 80 keV
/Generator/SingleParticle/max_energy 80 keV

## Nexus Physics List
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  true

#GEOMETRY
/Geometry/KingCRAB/gas_pressure 5. bar
/Geometry/KingCRAB/max_step_size 1 mm

# PERSISTENCY
/nexus/random_seed            9
/nexus/persistency/start_id   0
/nexus/persistency/output_file KingCRAB_GammaGen
