## ----------------------------------------------------------------------------
## nexus | KingCRAB_GammaGen.init.mac
##
## Initialization macro to simulate complete Ba-133 decays in KingCRAB
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------


/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics
/PhysicsList/RegisterPhysics G4OpticalPhysics

/nexus/RegisterGeometry KingCRAB

/nexus/RegisterGenerator IonGenerator

/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterRunAction DefaultRunAction
/nexus/RegisterTrackingAction DefaultTrackingAction
/nexus/RegisterSteppingAction SaveAllSteppingAction

/nexus/RegisterMacro macros/KingCRAB_GammaGen.config.mac
